version: '3'
services:
  app:
    container_name: cargo-app
    image: latest/cargo-app
    build: .
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongo
      - DB_USER=test
      - DB_PASSWORD=qwe
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=qwe
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    command: mongod
